import { prisma } from "../helpers/prisma.js";

export const seedNutrition = async () => {
  try {
    const foodCount = await prisma.food.count();
    const recipeCount = await prisma.recipe.count();

    if (foodCount > 0 && recipeCount > 0) {
      console.log("[Nutrition Seed] Foods and recipes already seeded.");
      return;
    }

    const foodData = [
      { "emoji": "🥩", "name": "Beef (lean)", "cat": "protein", "phases": ["menstrual", "follicular", "ovulatory", "luteal"], "why": "Rich in haem iron — the most absorbable form. Critical during menstruation to replace blood iron losses. Also provides zinc (supports ovulation) and B12 (energy metabolism).", "macros": { "cal": "215", "pro": "26g", "carb": "0g", "fat": "12g" } },
      { "emoji": "🐟", "name": "Salmon", "cat": "protein", "phases": ["menstrual", "luteal", "follicular"], "why": "Exceptional source of omega-3 fatty acids (EPA/DHA) which directly reduce prostaglandin-driven inflammation. Menstrual and luteal phase essential. Also provides vitamin D and selenium.", "macros": { "cal": "208", "pro": "20g", "carb": "0g", "fat": "13g" } },
      { "emoji": "🐓", "name": "Chicken Breast", "cat": "protein", "phases": ["follicular", "ovulatory", "luteal"], "why": "Lean, complete protein supporting muscle protein synthesis. High in B6 which supports serotonin production — particularly useful in the luteal phase for mood management.", "macros": { "cal": "165", "pro": "31g", "carb": "0g", "fat": "3.6g" } },
      { "emoji": "🥚", "name": "Eggs", "cat": "protein", "phases": ["follicular", "ovulatory", "menstrual", "luteal"], "why": "Complete protein with all essential amino acids. Rich in choline (brain health, oestrogen metabolism), B12, and vitamin D. The yolk contains cholesterol — the raw material for hormone synthesis.", "macros": { "cal": "155", "pro": "13g", "carb": "1g", "fat": "11g" } },
      { "emoji": "🫘", "name": "Lentils", "cat": "protein", "phases": ["menstrual", "luteal", "follicular"], "why": "Non-haem iron paired with folate — critical for blood replenishment during menstruation. High fibre supports oestrogen clearance via the gut microbiome.", "macros": { "cal": "116", "pro": "9g", "carb": "20g", "fat": "0.4g" } },
      { "emoji": "🐟", "name": "Sardines", "cat": "protein", "phases": ["menstrual", "luteal"], "why": "Extremely high in omega-3s, calcium, and vitamin D. One of the best anti-inflammatory proteins — ideal for menstrual cramping and luteal phase PMS.", "macros": { "cal": "208", "pro": "25g", "carb": "0g", "fat": "11g" } },
      { "emoji": "🫛", "name": "Chickpeas", "cat": "protein", "phases": ["follicular", "luteal", "menstrual"], "why": "Contains zinc (follicle development), iron, and folate. High fibre supports the estrobolome (gut bacteria that metabolise oestrogen).", "macros": { "cal": "164", "pro": "9g", "carb": "27g", "fat": "2.6g" } },
      { "emoji": "🫘", "name": "Black Beans", "cat": "protein", "phases": ["menstrual", "luteal", "follicular"], "why": "Iron, magnesium, and fibre triple. Magnesium content directly reduces menstrual cramping and PMS mood symptoms.", "macros": { "cal": "132", "pro": "9g", "carb": "24g", "fat": "0.5g" } },
      { "emoji": "🥊", "name": "Turkey", "cat": "protein", "phases": ["luteal", "follicular"], "why": "Very high in tryptophan — the precursor to serotonin. Essential in the luteal phase when falling oestrogen drops serotonin. Also high in B6 and zinc.", "macros": { "cal": "189", "pro": "29g", "carb": "0g", "fat": "7g" } },
      { "emoji": "🫘", "name": "Tofu", "cat": "protein", "phases": ["follicular", "menstrual"], "why": "Complete plant protein with isoflavones that support gentle oestrogen activity. Excellent iron source for vegetarians.", "macros": { "cal": "76", "pro": "8g", "carb": "2g", "fat": "4g" } },
      { "emoji": "🍠", "name": "Sweet Potato", "cat": "carbs", "phases": ["luteal", "menstrual", "follicular"], "why": "Complex carbohydrate that raises serotonin — directly addressing luteal-phase mood dips. High in beta-carotene, vitamin C, and potassium.", "macros": { "cal": "86", "pro": "1.6g", "carb": "20g", "fat": "0.1g" } },
      { "emoji": "🌾", "name": "Oats", "cat": "carbs", "phases": ["follicular", "luteal", "menstrual"], "why": "Slow-release carbohydrate with beta-glucan fibre — stabilises blood sugar. Contains zinc and iron — ideal menstrual-phase breakfast.", "macros": { "cal": "389", "pro": "17g", "carb": "66g", "fat": "7g" } },
      { "emoji": "🍚", "name": "Brown Rice", "cat": "carbs", "phases": ["follicular", "ovulatory"], "why": "Complex carbohydrate ideal for fuelling high-intensity training. Rich in B vitamins and manganese.", "macros": { "cal": "216", "pro": "5g", "carb": "45g", "fat": "1.8g" } },
      { "emoji": "🌿", "name": "Quinoa", "cat": "carbs", "phases": ["follicular", "ovulatory", "menstrual"], "why": "Complete protein AND complex carb. Iron, magnesium, and folate make it particularly valuable during menstruation.", "macros": { "cal": "222", "pro": "8g", "carb": "39g", "fat": "3.5g" } },
      { "emoji": "🌾", "name": "Buckwheat", "cat": "carbs", "phases": ["luteal", "menstrual"], "why": "Rich in rutin — reduces heavy menstrual bleeding by strengthening capillary walls. High magnesium reduces cramping. Gluten-free.", "macros": { "cal": "343", "pro": "13g", "carb": "72g", "fat": "3.4g" } },
      { "emoji": "🥑", "name": "Avocado", "cat": "fats", "phases": ["luteal", "menstrual", "follicular", "ovulatory"], "why": "Monounsaturated fats are building blocks for steroid hormones. Rich in B5 (adrenal support), vitamin E (egg quality), potassium (reduces bloating).", "macros": { "cal": "160", "pro": "2g", "carb": "9g", "fat": "15g" } },
      { "emoji": "🫒", "name": "Olive Oil", "cat": "fats", "phases": ["luteal", "menstrual", "follicular", "ovulatory"], "why": "Oleocanthal has direct anti-inflammatory action. Supports cell membrane integrity crucial for hormone receptor sensitivity.", "macros": { "cal": "884", "pro": "0g", "carb": "0g", "fat": "100g" } },
      { "emoji": "🌰", "name": "Walnuts", "cat": "fats", "phases": ["menstrual", "luteal", "follicular"], "why": "Best plant-based source of ALA omega-3. Contains melatonin (improves luteal-phase sleep). Rich in vitamin E for egg protection.", "macros": { "cal": "654", "pro": "15g", "carb": "14g", "fat": "65g" } },
      { "emoji": "🥜", "name": "Almonds", "cat": "fats", "phases": ["luteal", "follicular"], "why": "High in magnesium, vitamin E, and calcium — the trifecta for PMS relief. Vitamin E supports progesterone production.", "macros": { "cal": "579", "pro": "21g", "carb": "22g", "fat": "50g" } },
      { "emoji": "🫘", "name": "Flaxseed", "cat": "fats", "phases": ["menstrual", "follicular", "luteal"], "why": "Highest plant source of lignans which modulate oestrogen. Omega-3 ALA reduces menstrual inflammation. Ground flaxseed = far more bioavailable.", "macros": { "cal": "534", "pro": "18g", "carb": "29g", "fat": "42g" } },
      { "emoji": "🌻", "name": "Pumpkin Seeds", "cat": "fats", "phases": ["follicular", "menstrual"], "why": "Remarkably high in zinc — critical for follicle development, LH surge, and ovulation. Iron replaces menstrual losses.", "macros": { "cal": "559", "pro": "30g", "carb": "11g", "fat": "49g" } },
      { "emoji": "🫘", "name": "Chia Seeds", "cat": "fats", "phases": ["menstrual", "luteal", "follicular"], "why": "Omega-3s, calcium, iron, and magnesium in one seed. ALA reduces prostaglandin inflammation.", "macros": { "cal": "486", "pro": "17g", "carb": "42g", "fat": "31g" } },
      { "emoji": "🥦", "name": "Broccoli", "cat": "veg", "phases": ["ovulatory", "follicular", "luteal"], "why": "Contains DIM which supports healthy oestrogen metabolism. Sulforaphane activates anti-inflammatory pathways. Critical for oestrogen detoxification at ovulation.", "macros": { "cal": "34", "pro": "2.8g", "carb": "7g", "fat": "0.4g" } },
      { "emoji": "🥬", "name": "Spinach", "cat": "veg", "phases": ["menstrual", "follicular", "luteal"], "why": "Richest leafy green for non-haem iron. Folate for DNA synthesis and mood. Vitamin K for blood health.", "macros": { "cal": "23", "pro": "2.9g", "carb": "3.6g", "fat": "0.4g" } },
      { "emoji": "🥬", "name": "Kale", "cat": "veg", "phases": ["menstrual", "ovulatory", "luteal"], "why": "Calcium, vitamin K, and iron. Sulforaphane and glucosinolates support liver oestrogen detoxification.", "macros": { "cal": "49", "pro": "4.3g", "carb": "9g", "fat": "0.9g" } },
      { "emoji": "🥕", "name": "Carrots", "cat": "veg", "phases": ["luteal", "follicular"], "why": "Raw carrots contain unique fibre that binds excess oestrogen in the gut — supporting hormonal balance. Rich in beta-carotene.", "macros": { "cal": "41", "pro": "0.9g", "carb": "10g", "fat": "0.2g" } },
      { "emoji": "🫑", "name": "Red Pepper", "cat": "veg", "phases": ["follicular", "ovulatory", "menstrual"], "why": "Highest vitamin C content of all vegetables. Vitamin C is essential for iron absorption — pair with iron foods.", "macros": { "cal": "31", "pro": "1g", "carb": "6g", "fat": "0.3g" } },
      { "emoji": "🍄", "name": "Mushrooms", "cat": "veg", "phases": ["menstrual", "luteal"], "why": "The only non-animal food with significant vitamin D. Vitamin D has documented effects on reducing PMS severity.", "macros": { "cal": "22", "pro": "3.1g", "carb": "3.3g", "fat": "0.3g" } },
      { "emoji": "🫚", "name": "Beetroot", "cat": "veg", "phases": ["menstrual", "follicular"], "why": "Rich in iron and folate for blood building. Nitrates improve oxygen delivery for cardiovascular performance in training.", "macros": { "cal": "43", "pro": "1.6g", "carb": "10g", "fat": "0.2g" } },
      { "emoji": "🍅", "name": "Tomatoes", "cat": "veg", "phases": ["follicular", "ovulatory"], "why": "Lycopene — protects eggs from oxidative damage and supports endometrial health. Best absorbed when cooked with fat.", "macros": { "cal": "18", "pro": "0.9g", "carb": "3.9g", "fat": "0.2g" } },
      { "emoji": "🫐", "name": "Blueberries", "cat": "fruit", "phases": ["menstrual", "ovulatory", "luteal"], "why": "Anthocyanins are among the most potent antioxidants — protect eggs from oxidative damage and cross the blood-brain barrier to support mood.", "macros": { "cal": "57", "pro": "0.7g", "carb": "14g", "fat": "0.3g" } },
      { "emoji": "🍓", "name": "Strawberries", "cat": "fruit", "phases": ["follicular", "ovulatory"], "why": "Highest vitamin C of common berries — supports iron absorption and collagen synthesis. Folate for hormone synthesis.", "macros": { "cal": "32", "pro": "0.7g", "carb": "7.7g", "fat": "0.3g" } },
      { "emoji": "🍌", "name": "Banana", "cat": "fruit", "phases": ["luteal", "follicular"], "why": "High in B6 (serotonin synthesis — critical for luteal mood), potassium (reduces fluid retention), and magnesium.", "macros": { "cal": "89", "pro": "1.1g", "carb": "23g", "fat": "0.3g" } },
      { "emoji": "🍒", "name": "Cherries", "cat": "fruit", "phases": ["menstrual", "luteal"], "why": "Melatonin and anthocyanins — improves sleep quality while providing anti-inflammatory compounds similar to ibuprofen.", "macros": { "cal": "50", "pro": "1g", "carb": "12g", "fat": "0.3g" } },
      { "emoji": "🍇", "name": "Grapes (red)", "cat": "fruit", "phases": ["ovulatory", "luteal"], "why": "Resveratrol has anti-inflammatory and antioxidant effects and supports healthy oestrogen receptor activity.", "macros": { "cal": "67", "pro": "0.6g", "carb": "17g", "fat": "0.4g" } },
      { "emoji": "🍊", "name": "Orange", "cat": "fruit", "phases": ["menstrual", "follicular"], "why": "Vitamin C + folate combination — boosts iron absorption while supporting the follicular cycle. Anti-inflammatory hesperidin in the pith.", "macros": { "cal": "47", "pro": "0.9g", "carb": "12g", "fat": "0.1g" } },
      { "emoji": "🥛", "name": "Greek Yoghurt", "cat": "dairy", "phases": ["luteal", "follicular", "ovulatory"], "why": "Calcium supplementation reduces PMS severity by up to 50% in clinical trials. Provides calcium and probiotics supporting oestrogen metabolism.", "macros": { "cal": "97", "pro": "10g", "carb": "4g", "fat": "5g" } },
      { "emoji": "🧀", "name": "Cottage Cheese", "cat": "dairy", "phases": ["follicular", "ovulatory"], "why": "Very high protein with low fat — ideal for follicular phase muscle building. Casein protein is excellent before bed.", "macros": { "cal": "206", "pro": "25g", "carb": "6g", "fat": "9g" } },
      { "emoji": "🥛", "name": "Kefir", "cat": "dairy", "phases": ["follicular", "luteal", "menstrual"], "why": "Probiotic powerhouse — directly supports the estrobolome, improving oestrogen clearance. Evidence for mood improvement through gut-brain axis.", "macros": { "cal": "61", "pro": "3.5g", "carb": "5g", "fat": "3.3g" } },
      { "emoji": "🍫", "name": "Dark Chocolate (85%+)", "cat": "supplements", "phases": ["luteal", "menstrual"], "why": "Magnesium content rivals supplements — directly reduces cramping and mood symptoms. Cravings for chocolate in the luteal phase are a genuine magnesium signal.", "macros": { "cal": "598", "pro": "8g", "carb": "46g", "fat": "43g" } },
      { "emoji": "🫚", "name": "Turmeric", "cat": "supplements", "phases": ["menstrual", "luteal"], "why": "Curcumin is a COX-2 inhibitor — the same pathway as ibuprofen but gentler. Shown to reduce menstrual pain comparable to NSAIDs. Add black pepper for 2000% better absorption.", "macros": { "cal": "354", "pro": "8g", "carb": "65g", "fat": "10g" } },
      { "emoji": "🌿", "name": "Ginger", "cat": "supplements", "phases": ["menstrual", "luteal"], "why": "Shown in RCTs to reduce menstrual pain as effectively as ibuprofen at 750–2000mg/day. Also reduces prostaglandin synthesis.", "macros": { "cal": "80", "pro": "1.8g", "carb": "18g", "fat": "0.8g" } },
      { "emoji": "🍵", "name": "Chamomile Tea", "cat": "supplements", "phases": ["menstrual", "luteal"], "why": "Apigenin reduces anxiety via GABA receptors. Glycine relaxes uterine muscle — clinically shown to reduce menstrual cramps.", "macros": { "cal": "0", "pro": "0g", "carb": "0g", "fat": "0g" } },
      { "emoji": "🌿", "name": "Ashwagandha", "cat": "supplements", "phases": ["luteal", "menstrual"], "why": "Adaptogen that reduces cortisol (elevated in late luteal phase), improves thyroid function, and reduces anxiety — relevant to PMS management.", "macros": { "cal": "—", "pro": "—", "carb": "—", "fat": "—" } },
      { "emoji": "🌰", "name": "Brazil Nuts", "cat": "fats", "phases": ["ovulatory", "follicular"], "why": "The single best dietary source of selenium — 2-3 nuts exceed the daily requirement. Selenium is critical for thyroid hormone, antioxidant defence of eggs, and the LH surge.", "macros": { "cal": "659", "pro": "14g", "carb": "12g", "fat": "67g" } },
      { "emoji": "🍵", "name": "Green Tea", "cat": "supplements", "phases": ["follicular", "ovulatory"], "why": "EGCG supports follicle quality and protects eggs from oxidative damage. L-theanine provides calm focus — ideal for follicular phase productivity.", "macros": { "cal": "0", "pro": "0g", "carb": "0g", "fat": "0g" } },
      { "emoji": "🫙", "name": "Fermented Foods", "cat": "supplements", "phases": ["follicular", "ovulatory", "luteal"], "why": "Kimchi, sauerkraut, miso — probiotic foods directly support the estrobolome (gut bacteria that metabolise oestrogen).", "macros": { "cal": "15", "pro": "1g", "carb": "3g", "fat": "0.1g" } },
      { "emoji": "🌿", "name": "Cinnamon", "cat": "supplements", "phases": ["luteal", "menstrual"], "why": "Regulates blood sugar and insulin sensitivity — directly relevant given the luteal-phase drop in insulin sensitivity.", "macros": { "cal": "247", "pro": "4g", "carb": "81g", "fat": "1.2g" } }
    ];

    const recipesData = [
      { "emoji": "🍲", "name": "Red Lentil Iron Soup", "phases": ["menstrual"], "meal": "dinner", "prepTime": "25 min", "cals": "320", "tagline": "A blood-building bowl of warmth for heavy flow days", "why": "Red lentils provide non-haem iron, folate, and magnesium. Tomatoes and lemon juice provide vitamin C to maximise iron absorption. Turmeric and ginger reduce prostaglandin-driven inflammation.", "macros": { "cal": "320", "pro": "18g", "carb": "48g", "fat": "6g" }, "ingredients": [{ "n": "Red lentils", "a": "200g" }, { "n": "Vegetable stock", "a": "1L" }, { "n": "Tinned tomatoes", "a": "400g" }, { "n": "Onion", "a": "1 large" }, { "n": "Garlic", "a": "3 cloves" }, { "n": "Fresh ginger", "a": "2cm" }, { "n": "Turmeric", "a": "1 tsp" }, { "n": "Lemon juice", "a": "1 lemon" }, { "n": "Spinach", "a": "2 handfuls" }, { "n": "Olive oil", "a": "1 tbsp" }], "steps": ["Sauté onion and garlic in olive oil for 5 minutes until soft.", "Add grated ginger, turmeric, and cumin. Stir for 60 seconds.", "Add rinsed lentils, tinned tomatoes, and stock. Simmer 20 minutes.", "Stir in spinach and allow to wilt for 2 minutes.", "Squeeze in lemon juice before serving to maximise iron absorption."] },
      { "emoji": "🥣", "name": "Ginger Anti-Cramp Porridge", "phases": ["menstrual"], "meal": "breakfast", "prepTime": "10 min", "cals": "385", "tagline": "Warm, soothing oats with cramp-fighting ingredients", "why": "Oats provide magnesium and iron. Ginger reduces menstrual pain clinically comparably to ibuprofen. Banana provides B6 for serotonin. Dark chocolate chips add magnesium and comfort.", "macros": { "cal": "385", "pro": "12g", "carb": "58g", "fat": "11g" }, "ingredients": [{ "n": "Rolled oats", "a": "80g" }, { "n": "Oat milk", "a": "300ml" }, { "n": "Fresh ginger, grated", "a": "1 tsp" }, { "n": "Cinnamon", "a": "1/2 tsp" }, { "n": "Banana", "a": "1" }, { "n": "Chia seeds", "a": "1 tbsp" }, { "n": "Dark chocolate chips", "a": "15g" }, { "n": "Honey", "a": "1 tsp" }], "steps": ["Bring milk to a simmer. Add oats and a pinch of salt.", "Stir in grated ginger and cinnamon.", "Cook on medium-low for 5-7 minutes, stirring regularly.", "Pour into a bowl and top with banana, chia seeds, dark chocolate chips, and honey."] },
      { "emoji": "🐟", "name": "Omega-3 Salmon Bowl", "phases": ["menstrual", "luteal"], "meal": "lunch", "prepTime": "20 min", "cals": "520", "tagline": "EPA and DHA to fight inflammation at the source", "why": "Salmon is the most effective dietary source of EPA/DHA omega-3s, which directly reduce prostaglandin synthesis — the cause of menstrual cramping.", "macros": { "cal": "520", "pro": "38g", "carb": "42g", "fat": "18g" }, "ingredients": [{ "n": "Salmon fillet", "a": "180g" }, { "n": "Brown rice, cooked", "a": "150g" }, { "n": "Spinach", "a": "2 handfuls" }, { "n": "Cucumber", "a": "half" }, { "n": "Avocado", "a": "half" }, { "n": "Lemon", "a": "1" }, { "n": "Soy sauce", "a": "1 tbsp" }, { "n": "Sesame seeds", "a": "1 tbsp" }], "steps": ["Season salmon with ginger, lemon juice, and salt. Pan-fry for 12-14 minutes.", "Build bowl: brown rice base, fresh spinach, sliced cucumber and avocado.", "Place cooked salmon on top. Drizzle with soy sauce and olive oil.", "Scatter sesame seeds and an extra squeeze of lemon."] },
      { "emoji": "🍫", "name": "Magnesium Bliss Balls", "phases": ["menstrual", "luteal"], "meal": "snack", "prepTime": "15 min", "cals": "185", "tagline": "No-bake energy balls loaded with magnesium", "why": "Dark chocolate, almonds, cashews, and chia seeds are all high in magnesium — the mineral most effective for reducing cramping and mood symptoms.", "macros": { "cal": "185", "pro": "5g", "carb": "16g", "fat": "12g" }, "ingredients": [{ "n": "Medjool dates", "a": "10" }, { "n": "Dark chocolate (85%)", "a": "50g" }, { "n": "Almonds", "a": "80g" }, { "n": "Cashews", "a": "40g" }, { "n": "Chia seeds", "a": "2 tbsp" }, { "n": "Cacao powder", "a": "1 tbsp" }, { "n": "Sea salt", "a": "pinch" }], "steps": ["Pulse almonds and cashews until a rough meal forms.", "Add pitted dates and cacao powder. Blend until clumping.", "Add melted chocolate, chia seeds, and salt. Pulse to combine.", "Roll into 12-14 balls. Refrigerate 30 minutes to firm up."] },
      { "emoji": "🫗", "name": "Golden Milk Latte", "phases": ["menstrual", "luteal"], "meal": "snack", "prepTime": "5 min", "cals": "120", "tagline": "Anti-inflammatory curcumin drink with maximum bioavailability", "why": "Turmeric's curcumin directly reduces prostaglandin synthesis. Black pepper increases curcumin absorption by 2000%.", "macros": { "cal": "120", "pro": "4g", "carb": "14g", "fat": "4g" }, "ingredients": [{ "n": "Oat or almond milk", "a": "300ml" }, { "n": "Turmeric powder", "a": "1 tsp" }, { "n": "Ground ginger", "a": "1/2 tsp" }, { "n": "Cinnamon", "a": "1/4 tsp" }, { "n": "Black pepper", "a": "good pinch" }, { "n": "Honey", "a": "1 tsp" }], "steps": ["Warm milk in a small saucepan — do not boil.", "Whisk in turmeric, ginger, cinnamon, and a generous pinch of black pepper.", "Add honey. Froth if desired and pour into your mug."] },
      { "emoji": "🥗", "name": "Follicular Power Bowl", "phases": ["follicular", "ovulatory"], "meal": "lunch", "prepTime": "15 min", "cals": "480", "tagline": "A vibrant, energising bowl to match your rising oestrogen", "why": "Quinoa provides complete protein and iron. Edamame adds isoflavones to gently support rising oestrogen. Broccoli's DIM supports healthy oestrogen metabolism.", "macros": { "cal": "480", "pro": "26g", "carb": "52g", "fat": "16g" }, "ingredients": [{ "n": "Quinoa, cooked", "a": "150g" }, { "n": "Edamame", "a": "100g" }, { "n": "Broccoli florets", "a": "100g" }, { "n": "Rocket", "a": "2 handfuls" }, { "n": "Cherry tomatoes", "a": "10" }, { "n": "Pumpkin seeds", "a": "2 tbsp" }, { "n": "Feta cheese", "a": "40g" }, { "n": "Lemon + olive oil dressing", "a": "" }], "steps": ["Steam broccoli florets for 3-4 minutes until tender-crisp.", "Make dressing: whisk lemon juice, olive oil, minced garlic, and Dijon mustard.", "Build bowl: quinoa base, rocket, cherry tomatoes, edamame, and broccoli.", "Scatter pumpkin seeds and crumbled feta. Drizzle with dressing."] },
      { "emoji": "🍳", "name": "High-Protein Frittata", "phases": ["follicular", "ovulatory"], "meal": "breakfast", "prepTime": "20 min", "cals": "290", "tagline": "Lean protein to fuel follicular phase muscle building", "why": "Egg whites provide the cleanest lean protein for muscle protein synthesis. Whole eggs add choline for hormone synthesis. Asparagus adds folate for ovulation preparation.", "macros": { "cal": "290", "pro": "28g", "carb": "10g", "fat": "14g" }, "ingredients": [{ "n": "Whole eggs", "a": "3" }, { "n": "Egg whites", "a": "4" }, { "n": "Red pepper", "a": "1" }, { "n": "Asparagus", "a": "6 spears" }, { "n": "Spinach", "a": "large handful" }, { "n": "Feta cheese", "a": "30g" }], "steps": ["Preheat grill. Whisk whole eggs with egg whites. Season.", "Heat olive oil in an ovenproof pan. Sauté garlic, red pepper, and asparagus 3-4 min.", "Add spinach and stir until wilted. Pour egg mixture over vegetables.", "Cook on medium heat 3-4 minutes until edges set. Transfer under grill 3-4 min until golden."] },
      { "emoji": "🍗", "name": "Lemon Herb Chicken & Rice", "phases": ["follicular", "ovulatory"], "meal": "dinner", "prepTime": "35 min", "cals": "580", "tagline": "Clean, anabolic muscle-building dinner", "why": "Chicken breast is ideal for follicular phase muscle building — high in B6, B12, and complete amino acids. Brown rice fuels high-intensity training.", "macros": { "cal": "580", "pro": "52g", "carb": "56g", "fat": "14g" }, "ingredients": [{ "n": "Chicken breast", "a": "200g" }, { "n": "Brown rice, cooked", "a": "180g" }, { "n": "Broccoli", "a": "200g" }, { "n": "Lemon", "a": "1" }, { "n": "Garlic", "a": "3 cloves" }, { "n": "Fresh rosemary & thyme", "a": "2 sprigs each" }, { "n": "Olive oil", "a": "2 tbsp" }], "steps": ["Marinate chicken in lemon juice, olive oil, garlic, and herbs for 15+ minutes.", "Cook rice. Steam broccoli 5 minutes.", "Griddle chicken 4-5 minutes each side. Rest 3 minutes.", "Slice and serve over rice with broccoli. Drizzle with pan juices."] },
      { "emoji": "🥗", "name": "Cruciferous Oestrogen Salad", "phases": ["ovulatory", "follicular"], "meal": "lunch", "prepTime": "20 min", "cals": "380", "tagline": "DIM-rich salad for clean oestrogen clearance at peak", "why": "At ovulation, oestrogen peaks. This salad is built around cruciferous vegetables rich in DIM and I3C — supporting healthy oestrogen metabolism via the liver.", "macros": { "cal": "380", "pro": "14g", "carb": "28g", "fat": "24g" }, "ingredients": [{ "n": "Shredded kale", "a": "100g" }, { "n": "Broccoli florets (raw)", "a": "80g" }, { "n": "Red cabbage", "a": "80g" }, { "n": "Brussels sprouts, shaved", "a": "60g" }, { "n": "Sunflower seeds", "a": "2 tbsp" }, { "n": "Brazil nuts", "a": "25g" }, { "n": "Tahini dressing", "a": "" }], "steps": ["Massage kale with a pinch of salt and olive oil for 2 minutes.", "Thinly slice Brussels sprouts and combine with kale, raw broccoli, and shredded cabbage.", "Make tahini dressing: whisk tahini, lemon juice, minced garlic, water, and ACV.", "Toss salad in dressing. Scatter sunflower seeds and roughly chopped Brazil nuts."] },
      { "emoji": "🍝", "name": "Serotonin Pasta", "phases": ["luteal"], "meal": "dinner", "prepTime": "25 min", "cals": "580", "tagline": "Tryptophan + carbs = the biochemistry of comfort", "why": "Falling oestrogen in the luteal phase drops serotonin. Turkey is the highest dietary source of tryptophan (serotonin precursor). Carbs help tryptophan cross the blood-brain barrier.", "macros": { "cal": "580", "pro": "38g", "carb": "68g", "fat": "16g" }, "ingredients": [{ "n": "Wholemeal pasta", "a": "100g dry" }, { "n": "Turkey mince", "a": "200g" }, { "n": "Tinned tomatoes", "a": "400g" }, { "n": "Spinach", "a": "2 handfuls" }, { "n": "Onion", "a": "1" }, { "n": "Garlic", "a": "3 cloves" }, { "n": "Walnuts", "a": "30g" }, { "n": "Parmesan", "a": "20g" }], "steps": ["Cook pasta. Reserve pasta water before draining.", "Sauté onion and garlic. Add turkey mince and brown well.", "Add tinned tomatoes and season. Simmer 15 minutes. Stir in spinach.", "Toss with drained pasta. Top with crushed walnuts, basil, and grated parmesan."] },
      { "emoji": "🍫", "name": "Luteal Chocolate Mousse", "phases": ["luteal"], "meal": "snack", "prepTime": "10 min + 1hr chill", "cals": "220", "tagline": "Genuinely therapeutic chocolate — your hormones want this", "why": "Delivers magnesium (from dark chocolate and avocado), vitamin B6 (serotonin support), and healthy monounsaturated fats. Cravings for chocolate before your period are a genuine magnesium signal.", "macros": { "cal": "220", "pro": "4g", "carb": "18g", "fat": "15g" }, "ingredients": [{ "n": "Dark chocolate (85%)", "a": "80g" }, { "n": "Avocado (ripe)", "a": "1 large" }, { "n": "Cacao powder", "a": "1 tbsp" }, { "n": "Almond milk", "a": "2 tbsp" }, { "n": "Honey", "a": "1 tsp" }, { "n": "Sea salt", "a": "pinch" }], "steps": ["Melt dark chocolate gently. Allow to cool slightly.", "Blend ripe avocado until completely smooth.", "Add melted chocolate, cacao, almond milk, honey, vanilla, and salt. Blend until silky.", "Refrigerate for at least 1 hour until set. Top with sea salt flakes."] },
      { "emoji": "🥘", "name": "Slow Cooker Chicken & Sweet Potato", "phases": ["luteal"], "meal": "dinner", "prepTime": "10 min + 6hr cook", "cals": "490", "tagline": "Minimal effort, maximum nourishment for low-energy days", "why": "Sweet potato is the ultimate luteal-phase carb — raises serotonin, rich in beta-carotene (progesterone support), and potassium (reduces fluid retention).", "macros": { "cal": "490", "pro": "44g", "carb": "48g", "fat": "10g" }, "ingredients": [{ "n": "Chicken thighs (bone-in)", "a": "4" }, { "n": "Sweet potato", "a": "2 large" }, { "n": "Coconut milk", "a": "400ml" }, { "n": "Tinned tomatoes", "a": "400g" }, { "n": "Turmeric, cumin, coriander", "a": "1 tsp each" }, { "n": "Spinach", "a": "3 handfuls" }], "steps": ["Add everything except spinach to the slow cooker. Cube sweet potato.", "Cook on low 6-8 hours or high 3-4 hours.", "30 minutes before serving, stir in spinach.", "Shred the chicken with two forks — it will fall apart easily."] },
      { "emoji": "🍵", "name": "Hormone-Balancing Seed Pudding", "phases": ["luteal", "menstrual"], "meal": "breakfast", "prepTime": "5 min + overnight", "cals": "340", "tagline": "Chia, flax, and hemp — three seeds that work while you sleep", "why": "Chia seeds provide omega-3, calcium, and iron. Flaxseed provides lignans (oestrogen metabolism support). Hemp seeds provide GLA, magnesium, and complete protein.", "macros": { "cal": "340", "pro": "16g", "carb": "32g", "fat": "18g" }, "ingredients": [{ "n": "Chia seeds", "a": "3 tbsp" }, { "n": "Ground flaxseed", "a": "1 tbsp" }, { "n": "Hemp seeds", "a": "2 tbsp" }, { "n": "Almond milk", "a": "250ml" }, { "n": "Cinnamon + honey", "a": "to taste" }, { "n": "Mixed berries (to serve)", "a": "80g" }], "steps": ["Combine all seeds, milk, vanilla, cinnamon, and honey in a jar. Stir very well.", "Refrigerate overnight. The chia seeds will expand into a thick pudding.", "In the morning, stir and add a splash more milk if too thick.", "Top with mixed berries and a drizzle of almond butter."] }
    ]


    if (foodCount === 0) {
      for (const food of foodData) {
        await prisma.food.create({ data: food });
      }
      console.log(`[Nutrition Seed] Seeded ${foodData.length} foods successfully.`);
    }

    if (recipeCount === 0) {
      for (const recipe of recipesData) {
        await prisma.recipe.create({ data: recipe });
      }
      console.log(`[Nutrition Seed] Seeded ${recipesData.length} recipes successfully.`);
    }

  } catch (error) {
    console.error("[Nutrition Seed] Error seeding nutrition data:", error);
  }
};
